wandb:
  entity: kywch
  project: pokemon-g3
  group: ~

debug:
  env:
    headless: False
    stream_wrapper: False
    max_steps: 1024
    init_state: cut
  train:
    device: cuda
    compile: False
    compile_mode: default
    num_envs: 1
    envs_per_worker: 1
    envs_per_batch: 1
    batch_size: 128
    batch_rows: 32
    bptt_horizon: 4
    total_timesteps: 2000
    save_overlay: True
    overlay_interval: 4
    save_checkpoint: True
    checkpoint_interval: 4
    verbose: True
    env_pool: False

env:
  headless: True
  save_final_state: True
  print_rewards: True
  video_dir: video
  state_dir: pyboy_states
  init_state: Bulbasaur
  action_freq: 24
  max_steps: 655360
  save_video: False
  fast_video: False
  frame_stacks: 1
  perfect_ivs: True
  reduce_res: True

train:
  seed: 1
  torch_deterministic: True
  device: cuda
  compile: True
  compile_mode: "reduce-overhead"
  float32_matmul_precision: "high"
  total_timesteps: 200_000_000
  batch_size: 131072
  learning_rate: 2.0e-4
  anneal_lr: False
  gamma: 0.998
  gae_lambda: 0.95
  num_minibatches: 4
  update_epochs: 3
  norm_adv: True
  clip_coef: 0.1
  clip_vloss: True
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5
  target_kl: ~
  batch_rows: 128
  bptt_horizon: 16 #8
  vf_clip_coef: 0.12 # 0.1

  num_envs: 64
  envs_per_worker: 2
  envs_per_batch: 64
  env_pool: False

  verbose: True
  data_dir: runs
  save_overlay: True
  overlay_interval: 200
  save_checkpoint: False
  checkpoint_interval: 200
  cpu_offload: True
  pool_kernel: [0]

wrappers:
  baseline:
    - stream_wrapper.StreamWrapper:
        user: kywch

rewards:
  environment.CustomRewardEnv:
    reward:
      decay_frequency: 10
      decay_factor_coords: 0.9995
      decay_factor_npcs: 0.999
      decay_floor: 0.3
      weight_tile_exploration: 0.015
      weight_seen_npcs: 0.01
      weight_badge: 10.0
      weight_key_event: 4.0
      weight_map_progress: 4.0
      weight_max_opponent_level: 2.0
      weight_party_size: 2.0
      weight_level_cap: 60
      weight_over_level_multiplier: 0.25
      weight_learned_moves_with_item: 3.0
      weight_learned_moves: 0.1
      weight_seen_pokemon: 3.0
      weight_max_event: 1.0
      weight_hidden_obj: 0.02
      weight_menu_reward: 0.0001
      cooldown_menu_normal: 200
      cooldown_menu_boost: 10
      weight_cut_attempt: 0.01
      weight_cut_success: 10.0
      cooldown_cut: 100

policies:
  policy.ConvolutionalPolicy:
    policy:
      input_size: 512
      hidden_size: 512
      output_size: 512
      framestack: 3
      flat_size: 1920

    recurrent:
      # Assumed to be in the same module as the policy
      name: RecurrentWrapper
      input_size: 512
      hidden_size: 512
      num_layers: 1

  policy_multiconv.MultiConvolutionalPolicy:
    policy:
      input_size: 512
      hidden_size: 512
      output_size: 512
      framestack: 3  # not used for now
      flat_size: 2184  # not used for now

    recurrent:
      # Assumed to be in the same module as the policy
      name: RecurrentMultiConvolutionalWrapper
      input_size: 512
      hidden_size: 512
      num_layers: 1
