wandb:
  entity: kywch
  project: pokemon
  group: ~

debug:
  env:
    headless: False
    stream_wrapper: False
  train:
    device: cuda
    compile: False
    compile_mode: default
    num_envs: 1
    envs_per_worker: 1
    envs_per_batch: 1
    batch_size: 128
    batch_rows: 32
    bptt_horizon: 4
    total_timesteps: 1000
    save_overlay: True
    overlay_interval: 4
    save_checkpoint: True
    checkpoint_interval: 4
    verbose: True
    env_pool: False

env:
  headless: True
  save_final_state: True
  print_rewards: True
  video_dir: video
  state_dir: pyboy_states
  init_state: Bulbasaur
  action_freq: 24
  max_steps: 100_000_000
  save_video: False
  fast_video: False
  frame_stacks: 1
  perfect_ivs: True
  reduce_res: True

train:
  seed: 1
  torch_deterministic: True
  device: cuda
  compile: True
  compile_mode: "reduce-overhead"
  float32_matmul_precision: "high"
  total_timesteps: 100_000_000
  batch_size: 32768
  learning_rate: 2.5e-4
  anneal_lr: True
  gamma: 0.998
  gae_lambda: 0.95
  num_minibatches: 4
  update_epochs: 3
  norm_adv: True
  clip_coef: 0.1
  clip_vloss: True
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5
  target_kl: ~
  batch_rows: 128
  bptt_horizon: 16 #8
  vf_clip_coef: 0.12 # 0.1

  num_envs: 150
  envs_per_worker: 2
  envs_per_batch: 60
  env_pool: True

  verbose: True
  data_dir: runs
  save_overlay: True
  overlay_interval: 200
  save_checkpoint: False
  checkpoint_interval: 200
  cpu_offload: True
  pool_kernel: [0]

wrappers:
  baseline:
    - stream_wrapper.StreamWrapper:
        user: kywch
    - decay_exploration.DecayWrapper:
        step_forgetting_factor:
          npc: 0.995
          coords: 0.9995
          map_ids: 0.995
          explore: 0.9995
          start_menu: 0.998
          pokemon_menu: 0.998
          stats_menu: 0.998
          bag_menu: 0.998
          action_bag_menu: 0.998
        forgetting_frequency: 10

rewards:
  environment.CustomRewardEnv:
    reward:
      explore_weight: 3.0
      explore_npc_weight: 1.0
      explore_hidden_obj_weight: 1.0

policies:
  policy.ConvolutionalPolicy:
    policy:
      input_size: 512
      hidden_size: 512
      output_size: 512
      framestack: 3
      flat_size: 1920

    recurrent:
      # Assumed to be in the same module as the policy
      name: RecurrentWrapper
      input_size: 512
      hidden_size: 512
      num_layers: 1
